name:
  simulink_pipeline

on:
  workflow_dispatch:

permissions:
  checks:
    write

  contents:
    read


env:
  PATH_TO_MATLAB:
    C:/Program Files/MATLAB/R2025a/bin


jobs:
  Restore_Cache:
    runs-on:
      self-hosted

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Restore Cache

        uses:
          actions/cache@v4

        with:
          key:
            padv_artifacts-${{ github.run_id }}-${{ github.run_attempt }}

          restore-keys:
            padv_artifacts-cache

          path:
            |
            Code
            PA_Results/AHRS_Voter/metrics
            PA_Results/AHRS_Voter/model_standards_results
            PA_Results/test_results
            derived/artifacts.dmr


      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            padv_artifacts

          path:
            |
            derived/artifacts.dmr
            Code
            PA_Results/AHRS_Voter/metrics
            PA_Results/AHRS_Voter/model_standards_results
            PA_Results/test_results

          retention-days:
            30




  Runprocess:
    if:
      ${{ !cancelled() }}

    needs:
      Restore_Cache

    runs-on:
      self-hosted

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            padv_artifacts


      - name:
          Setup MATLAB

        run:
          echo "$PATH_TO_MATLAB" >> $GITHUB_PATH

      - name:
          Launch MATLAB

        run:
          >
          matlab 
          -nodesktop 
          -logfile output.log 
          -batch "openProject(pwd);runprocess(Process = 'CIPipeline', Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = false);" 

      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            padv_artifacts

          path:
            |
            derived/artifacts.dmr
            Code
            PA_Results/AHRS_Voter/metrics
            PA_Results/AHRS_Voter/model_standards_results
            PA_Results/test_results

          retention-days:
            30




  Generate_PADV_Report:
    if:
      ${{ !cancelled() }}

    needs:
      Runprocess

    runs-on:
      self-hosted

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            padv_artifacts


      - name:
          Setup MATLAB

        run:
          echo "$PATH_TO_MATLAB" >> $GITHUB_PATH

      - name:
          Generate PADV Report

        run:
          >
          matlab 
          -nodesktop 
          -logfile output.log 
          -batch "openProject(pwd);
          rptObj=padv.ProcessAdvisorReportGenerator(Process = 'CIPipeline', Format='pdf', OutputPath=fullfile(currentProject().RootFolder,'ProcessAdvisorReport'));
          rptObj.generateReport();" 

      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            padv_artifacts

          path:
            |
            derived/artifacts.dmr
            ProcessAdvisorReport.pdf

          retention-days:
            30




  Collect_Artifacts:
    if:
      ${{ !cancelled() }}

    needs:
      Generate_PADV_Report

    runs-on:
      self-hosted

    steps:
      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            padv_artifacts


      - name:
          Save Cache

        uses:
          actions/cache@v4

        with:
          key:
            padv_artifacts-cache-${{ github.sha }}

          path:
            |
            Code
            PA_Results/AHRS_Voter/metrics
            PA_Results/AHRS_Voter/model_standards_results
            PA_Results/test_results
            derived/artifacts.dmr





